// authActionTypes.js
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SET_USER_TYPE = "SET_USER_TYPE";
export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";
export const LOGOUT = "LOGOUT";
// export const UPDATE_USER_PROFILE_PIC = "UPDATE_USER_PROFILE_PIC";
// export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_STUDENT_LIST = "UPDATE_STUDENT_LIST";
